### ISSUE TITLE
Does not switch to note tab directly after creating a new ticket

### ISSUE THREAD

**Issue by groove9281** [clonemeagain/osticket-plugin-notefirst#1]
This is working great for me as long as I am viewing a previously created ticket.

However, if I go through the new ticket creation process and click open after filling out all of the new ticket details, I am taken to the ticket view and the Reply tab is still the default tab.

Is there any way to make this mod work for that situation too?

**Comment by clonemeagain** [comment]
Hmm, I'll check it out mate, cheers.

**Comment by clonemeagain** [comment]
I'm using the new_bootstrap method on mine, so it works. 
The default doesn't, and relies on  the regex from the attachments_preview plugin, which doesn't take into account every possible view. 
Guess I need to add one more!
Added an issue over there, will update when I've got it.

https://github.com/clonemeagain/attachment_preview/issues/7

**Comment by clonemeagain** [comment]
Ok, if you upgrade the attachment_preview plugin to the new version, it works properly now.

**Comment by groove9281** [comment]
After updating the plugin, all is now good.

Thank you!

**Comment by clonemeagain** [comment]
Sweet as bro, thanks for the update.
